  manifest:
    remotes:
      - name: zmkfirmware
        url-base: https://github.com/zmkfirmware
      - name: am0jackson
        url-base: https://github.com/am0jackson
    projects:
      - name: zmk
        remote: am0jackson
        revision: bbkeyboard_tp
        import: app/west.yml
    self:
      path: config
